#!/usr/bin/env bash

action=$1
shift
item=$1
shift

function usage {
	echo "  $(basename $0) [item]"
	echo "    Append date threshold to item."
	echo "    If item argument is omitted, all scheduled tasks are listed."
	echo "    Intended to be used with futureTasks \
              (http://github.com/FND/todo.txt-cli/blob/extensions/futureTasks)."
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

if [ "$item" = "" ]; then
	cat $TODO_FILE | grep " t:" # intentionally not enforcing date pattern
else
	$TODO_SH append $item "t:"`date -d "$*" +%F`
fi
